#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  BEGIN;
    CREATE TABLE IF NOT EXISTS users
    (
      id_user integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
      address character varying(100) COLLATE pg_catalog."default",
      date_birth character varying(100) COLLATE pg_catalog."default",
      doc_number character varying(30) COLLATE pg_catalog."default" NOT NULL,
      email character varying(150) COLLATE pg_catalog."default" NOT NULL,
      state boolean NOT NULL,
      last_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
      names character varying(50) COLLATE pg_catalog."default" NOT NULL,
      password character varying(100) COLLATE pg_catalog."default",
      phone character varying(100) COLLATE pg_catalog."default",
      state_vaccine boolean NOT NULL,
      user_name character varying(50) COLLATE pg_catalog."default",
      CONSTRAINT pk_user PRIMARY KEY (id_user),
      CONSTRAINT uk_user_docnumber UNIQUE (doc_number),
      CONSTRAINT uk_user_username UNIQUE (user_name)
    );

    CREATE TABLE IF NOT EXISTS vaccine
    (
      id_vaccine integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
      name character varying(50) COLLATE pg_catalog."default" NOT NULL,
      CONSTRAINT pk_vaccine PRIMARY KEY (id_vaccine)
    );

    CREATE TABLE IF NOT EXISTS user_vaccine
    (
      num_dosis character varying(5) COLLATE pg_catalog."default",
      date_vaccine character varying(30) COLLATE pg_catalog."default",
      id_user integer NOT NULL,
      id_vaccine integer NOT NULL,
      CONSTRAINT user_vaccine_pkey PRIMARY KEY (id_user, id_vaccine),
      CONSTRAINT fk_user_vaccine_vaccine FOREIGN KEY (id_vaccine)
          REFERENCES vaccine (id_vaccine) MATCH SIMPLE
          ON UPDATE NO ACTION
          ON DELETE NO ACTION,
      CONSTRAINT fk_user_vaccine_user FOREIGN KEY (id_user)
          REFERENCES users (id_user) MATCH SIMPLE
          ON UPDATE NO ACTION
          ON DELETE NO ACTION
    );

    CREATE TABLE IF NOT EXISTS rol
    (
      id_rol integer NOT NULL,
      description character varying(255) COLLATE pg_catalog."default",
      name character varying(255) COLLATE pg_catalog."default",
      CONSTRAINT pk_rol PRIMARY KEY (id_rol)
    );

    CREATE TABLE IF NOT EXISTS user_rol
    (
      id_user integer NOT NULL,
      id_rol integer NOT NULL,
      CONSTRAINT fk_user_rol_rol FOREIGN KEY (id_rol)
          REFERENCES rol (id_rol) MATCH SIMPLE
          ON UPDATE NO ACTION
          ON DELETE NO ACTION,
      CONSTRAINT fk_user_rol_user FOREIGN KEY (id_user)
          REFERENCES users (id_user) MATCH SIMPLE
          ON UPDATE NO ACTION
          ON DELETE NO ACTION
    );

    INSERT INTO vaccine(id_vaccine, name) VALUES(1, 'Sputnik');
    INSERT INTO vaccine(id_vaccine, name) VALUES(2, 'Astrazeneca');
    INSERT INTO vaccine(id_vaccine, name) VALUES(3, 'Pfizer');
    INSERT INTO vaccine(id_vaccine, name) VALUES(4, 'Jhonson&Jhonson');

    INSERT INTO rol(id_rol, name, description) VALUES (1, 'ADMIN', 'Admin');
    INSERT INTO rol(id_rol, name, description) VALUES (2, 'USER', 'User');
    INSERT INTO rol(id_rol, name, description) VALUES (3, 'DBA', 'DataBase administrator');

    INSERT INTO users(id_user, doc_number, names, last_name, email, user_name, password, state_vaccine, state) values (1, '123456', 'pepito', 'perez', 'daniel.10510@gmail.com', 'pepe', '\$2a\$10\$ckkkD0Avl/eJnH6GvsyxcOkbcPmzrXGRH54J0sk0VP/X0RW2fHqeq', false, true);

  COMMIT;

  
EOSQL