spring:
   mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: daniell.6900997@gmail.com
    password: Lu1?d?.69
    port: 587
    properties:
      mail:
        ssl:
          enable: true
        smtp:
          auth: true
          starttls:
            enable: true       
            required: true     
    protocol: smtp
    test-connection: true

#spring:
#   mail:
#    default-encoding: UTF-8
#    host: mail.sea.gob.bo
#    username: servicios@sea.gob.bo
#    password: yv}ZXUudKCz?
#    port: 587
#    properties:
#      mail:
#        ssl:
#          enable: true
#        smtp:
#          auth: true
#          starttls:
#            enable: true       
#            required: true     
#    protocol: smtp
#    test-connection: true

#spring:
#  mail:
#    port: 465
#    host: mail.sea.gob.bo
#    username: servicios@sea.gob.bo
#    password: yv}ZXUudKCz?
#    default-encoding: UTF-8
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true
#          auth: true
#          starttls:
#            enable: true
#            required: true
#    test-connection: true